### ISSUE TITLE
Shairport producing distortions in music feedback

### ISSUE THREAD

**Issue by ThorinDev** [AiGreek/Raspberry-Scripts#3]
It is very noticeable. It could be my pi but have cleaned and check connections but them seem fine

**Comment by Kazom** [comment]
The built in audio card in the pi isn't great if that is what you are using, this is most likely the answer. You will have much better luck using one like this via usb [https://www.amazon.com/gp/product/B00IRVQ0F8/ref=ox_sc_act_title_1?ie=UTF8&psc=1&smid=A29Y8OP2GPR7PE
](url)
Or if you are really crazy about sound something like this [https://www.hifiberry.com](url)

**Comment by ThorinDev** [comment]
Thanks. I didn't realise that. 👍
